-- MySQL Script generated by MySQL Workbench
-- 06/07/16 00:33:13
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Messages`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Messages` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Messages` (
  `messageid` INT NOT NULL AUTO_INCREMENT,
  `receive_userid` INT NULL,
  `sender_userid` INT NULL,
  `message` VARCHAR(45) NULL,
  `isread` TINYINT(1) NULL,
  PRIMARY KEY (`messageid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`User` ;

CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `userid` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(32) NOT NULL,
  `password` VARCHAR(128) NOT NULL,
  `avatar` VARCHAR(256) NULL,
  `iscompany` TINYINT(1) NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Datastore`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Datastore` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Datastore` (
  `userid` INT NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `middlename` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `dateofbirth` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `skype` VARCHAR(45) NULL,
  `emailpersonal` VARCHAR(45) NULL,
  `emailbusiness` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`userid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cards`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cards` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cards` (
  `userid` INT NOT NULL,
  `cardname` VARCHAR(45) NOT NULL,
  `firstname` VARCHAR(45) NULL,
  `middlename` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `dateofbirth` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `skype` VARCHAR(45) NULL,
  `emailpersonal` VARCHAR(45) NULL,
  `emailbusiness` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`userid`, `cardname`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cardshare`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Cardshare` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Cardshare` (
  `userid` INT NOT NULL,
  `cardname` VARCHAR(45) NOT NULL,
  `receiveduser` INT NOT NULL,
  PRIMARY KEY (`userid`, `cardname`, `receiveduser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Forms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Forms` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Forms` (
  `formid` INT NOT NULL AUTO_INCREMENT,
  `userid` INT NOT NULL,
  `receiveduser` INT NULL,
  `firstname` VARCHAR(45) NULL,
  `middlename` VARCHAR(45) NULL,
  `lastname` VARCHAR(45) NULL,
  `gender` VARCHAR(45) NULL,
  `dateofbirth` VARCHAR(45) NULL,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `town` VARCHAR(45) NULL,
  `facebook` VARCHAR(45) NULL,
  `twitter` VARCHAR(45) NULL,
  `skype` VARCHAR(45) NULL,
  `emailpersonal` VARCHAR(45) NULL,
  `emailbusiness` VARCHAR(45) NULL,
  `website` VARCHAR(45) NULL,
  PRIMARY KEY (`formid`, `userid`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
